_target_: rrnco.envs.atsp.ATSPEnv
name: atsp

generator_params:
  _target_: rrnco.envs.atsp.generator_lazy.LazyATSPGenerator
  num_loc: 100 # training graph_size
  tmat_class: False
  data_path: ../../../data/dataset
  file_name: splited_cities_list
  chunk_size: 1000  # 메모리 효율적인 청킹 크기
data_dir: ${paths.root_dir}/data/${env.name}

# Note that validation is not used for guiding training and this is already the test set
# so we can directly check the progress here!
val_file: [
  atsp_n100_seed3333_in_distribution.npz
]
val_dataloader_names: ["val"]
test_file: ${env.val_file}
