_target_: rrnco.envs.rcvrp.RCVRPEnv
name: rcvrp

generator_params:
  _target_: rrnco.envs.rcvrp.generator_lazy.LazyRCVRPGenerator
  num_loc: 100 # training graph_size
  data_path: ../../../data/dataset
  file_name: splited_cities_list
  chunk_size: 1000  # 메모리 효율적인 청킹 크기
data_dir: ${paths.root_dir}/data/${env.name}

# Note that validation is not used for guiding training and this is already the test set
# so we can directly check the progress here!
val_file: [
  "rcvrp_n100_seed3333_in_distribution.npz"
]
val_dataloader_names: ["val"]
test_file: ${env.val_file}
